### ISSUE TITLE
UX: Task form inaccuracies

### ISSUE THREAD

**Issue by pagenoare** [ofilipowicz/HustleGG-issues#10]
When I started using the app it felt like I can add more and more "Days of the week" records. Those buttons feel so much connected to it, that it confused me a bit.

What I suggest is to move them to the top right like other apps do it:
![file](https://user-images.githubusercontent.com/1623/52918456-7bfd0080-32f7-11e9-9e9b-833737b359c3.jpg)

**Comment by ofilipowicz** [comment]
I'm not sure what you mean by it. Could you explain it a bit more detailed?

**Comment by pagenoare** [comment]
If you can, please check how Slack app is doing the Save / Cancel buttons. Like for example the view which is triggered when you upload a file. 
![file 1](https://user-images.githubusercontent.com/1623/52920326-8e813500-330b-11e9-9f93-59a8fd7cfc22.jpg)

On the top left you have the Cancel button, on Right you have Send / OK button - as a user, those are the places where I look to confirm / cancel certain actions. On Add Task view you're having button "Add" which feels like I can add new row for "Days of the week", not like saving task itself.

Since on the left you have the "Go back" action, I included screenshot from Note app, as 2 buttons on the right are possible and fit well.

**Comment by ofilipowicz** [comment]
I see what you mean. Good idea.

**Comment by Dziemiano** [comment]
It also feels like you have to mark exact days of week you want not unmark, cause of same color patern  for unmarked days of week buttons as "Add" button.

**Comment by ofilipowicz** [comment]
Solved with verbal task description, changed button label from "Add" to "Save" and added line separator between buttons and form
