### ISSUE TITLE
Notifications settings

### ISSUE THREAD

**Issue by Dziemiano** [ofilipowicz/HustleGG-issues#20]
When i leave ex. 1 hour free time between activities it's for a reason. I don't need to add coffee/shower/whatever there but then app will inform that i have free time there. I'm aware of that. I would like to see 'hey you left 4/5 free hours today...' notification but don't feel the need of them between activities that are close to each other.

**Comment by ofilipowicz** [comment]
I'll add notifications settings.

**Comment by Dziemiano** [comment]
Just to highlight the issue.
![img_2009](https://user-images.githubusercontent.com/35170384/52960806-d9498e00-3399-11e9-88d6-86a065e1d934.jpg)

**Comment by ofilipowicz** [comment]
I'll add setting to turn them off. Later on there will be more customisable options.
