### ISSUE TITLE
Auto-close edit mode on tab change

### ISSUE THREAD

**Issue by pagenoare** [ofilipowicz/HustleGG-issues#5]
Steps to reproduce:

1) Go to Timeline tab
2) Click "Insert event" button
3) Navigate to "Activities" tab
4) "Activities" tab shows "I can't find any task right now" message.

If I go back to Timeline and cancel the insert event I can see activities just fine.

**Comment by ofilipowicz** [comment]
Works as intended. Activities list is empty as there is Event in progress. New Event can't be added from Activities list.

**Comment by pagenoare** [comment]
Well, technically I did not save the Event, so why would it be in progress? :)

**Comment by ofilipowicz** [comment]
Insert event adds new Event, it's just in edit mode by default

**Comment by ofilipowicz** [comment]
Changed issue title. It will be handled in future version.

**Comment by ofilipowicz** [comment]
Turns out it's very complicated from implementation side. Postponed for now.
